// ESLint 9 flat config for wfmlabs-hub (Next.js 15 + TypeScript + Payload CMS).
//
// Goal: keep `bun run lint` usable repo-wide without flooding a 23k-line, 118-file
// codebase with new errors. We run typescript-eslint's *non* type-checked recommended
// set (fast, no full type graph) plus the Next.js core rules. The noisiest rules that
// would otherwise fire across existing, working code are relaxed to `warn` (or off)
// so a clean lint pass is achievable. Tighten incrementally in follow-ups.
//
// Formatting is owned by Prettier (`bun run format`), so eslint-config-prettier turns
// off any stylistic rules that would conflict.

import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import nextPlugin from '@next/eslint-plugin-next'
import prettier from 'eslint-config-prettier'
import globals from 'globals'

export default tseslint.config(
  // Never lint generated, vendored, or build artifacts.
  {
    ignores: [
      '.next/**',
      'out/**',
      'build/**',
      'dist/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'node_modules/**',
      'public/roc/**', // OpenMCT dist + dashboards (vendored / hand-authored JS)
      'src/types/payload-types.ts', // generated by `payload generate:types`
      'src/app/(payload)/admin/importMap.js', // generated by `payload generate:importmap`
      'src/migrations/**', // Payload migration snapshots (generated)
      'next-env.d.ts',
      '*.tgz',
    ],
  },

  // Base JS + TS recommended (non type-checked: no parserOptions.project).
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // Next.js core-web-vitals rule set.
  {
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  // Project-wide language options + relaxed ruleset.
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      // Relaxed to warn: present across existing code, not worth blocking lint on.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // Payload/Next code legitimately uses `require`-style and empty interfaces in places.
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      // Allow intentional non-null assertions (Payload field access patterns).
      '@typescript-eslint/no-non-null-assertion': 'off',

      // The Next.js page-link rule fires on `<a href="/admin/...">` and
      // `<a href="/api/...">` — those target the Payload admin app and API
      // route handlers, which are NOT Next.js pages, so `<Link>` is wrong there.
      // Keep as a warning rather than a build-blocking error.
      '@next/next/no-html-link-for-pages': 'warn',
      '@next/next/no-img-element': 'warn',

      // Pre-existing, low-severity patterns across the existing codebase
      // (empty catch blocks, literal regex escapes). Surfaced as warnings so
      // lint passes; clean up incrementally rather than blocking on them.
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-useless-escape': 'warn',
    },
  },

  // Config/script files run in Node; allow console + Node globals.
  {
    files: ['*.{js,mjs,cjs,ts}', 'scripts/**/*.{js,ts}'],
    languageOptions: { globals: { ...globals.node } },
  },

  // Disable stylistic rules that conflict with Prettier (Prettier owns formatting).
  prettier,
)
