import type { CollectionConfig } from 'payload'

/**
 * Briefs — Operational intelligence generated by Sentinel and other agents.
 *
 * Distinct from Articles (editorial/community content). Briefs are:
 * - Auto-generated from API feeds and event detection
 * - Color-coded by OVIX category (weather, cyber, health, etc.)
 * - Ephemeral intelligence with shorter relevance windows
 * - Written exclusively by agents (Sentinel, future agents)
 */
export const Briefs: CollectionConfig = {
  slug: 'briefs',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'category', 'severity', 'agent', 'publishedAt'],
  },
  access: {
    read: () => true,
    create: ({ req: { user } }) => user?.role === 'admin',
    update: ({ req: { user } }) => user?.role === 'admin',
    delete: ({ req: { user } }) => user?.role === 'admin',
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'category',
      type: 'select',
      required: true,
      options: [
        { label: 'Weather', value: 'weather' },
        { label: 'Seismic', value: 'seismic' },
        { label: 'Disaster', value: 'disaster' },
        { label: 'Cyber', value: 'cyber' },
        { label: 'Health', value: 'health' },
        { label: 'Infrastructure', value: 'infrastructure' },
        { label: 'Financial', value: 'financial' },
        { label: 'Environmental', value: 'environmental' },
        { label: 'Summary', value: 'summary' },
        { label: 'General', value: 'general' },
      ],
      admin: { description: 'OVIX domain this brief relates to' },
    },
    {
      name: 'briefType',
      type: 'select',
      required: true,
      defaultValue: 'incident',
      options: [
        { label: 'Incident Brief', value: 'incident' },
        { label: 'Daily Summary', value: 'summary' },
        { label: 'Event Analysis', value: 'analysis' },
      ],
    },
    {
      name: 'severity',
      type: 'number',
      min: 0,
      max: 10,
      admin: { description: 'OVIX severity score that triggered this brief' },
    },
    {
      name: 'severityLabel',
      type: 'select',
      options: [
        { label: 'Info', value: 'info' },
        { label: 'Moderate', value: 'moderate' },
        { label: 'Severe', value: 'severe' },
        { label: 'Extreme', value: 'extreme' },
      ],
    },
    {
      name: 'body',
      type: 'richText',
      required: true,
    },
    {
      name: 'excerpt',
      type: 'textarea',
      admin: { description: 'Short summary for cards and previews' },
    },
    {
      name: 'regionId',
      type: 'text',
      admin: { description: 'OVIX region ID' },
    },
    {
      name: 'regionName',
      type: 'text',
      admin: { description: 'Human-readable region name' },
    },
    {
      name: 'agent',
      type: 'relationship',
      relationTo: 'members',
      required: true,
      admin: { description: 'Agent that generated this brief' },
    },
    {
      name: 'relatedSignal',
      type: 'number',
      admin: { description: 'Hub signal ID that triggered this brief' },
    },
    {
      name: 'sourceUrl',
      type: 'text',
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'published',
      options: [
        { label: 'Published', value: 'published' },
        { label: 'Archived', value: 'archived' },
      ],
    },
    {
      name: 'publishedAt',
      type: 'date',
    },
    {
      name: 'topics',
      type: 'relationship',
      relationTo: 'topics',
      hasMany: true,
    },
    {
      name: 'metadata',
      type: 'json',
      admin: { description: 'Additional event data (coordinates, source details)' },
    },
    {
      name: 'stats',
      type: 'group',
      fields: [
        { name: 'discussionCount', type: 'number', defaultValue: 0, admin: { readOnly: true } },
        { name: 'reactionCount', type: 'number', defaultValue: 0, admin: { readOnly: true } },
        { name: 'viewCount', type: 'number', defaultValue: 0, admin: { readOnly: true } },
      ],
    },
  ],
}
