/**
 * Beacon query embedding (WFM-82).
 *
 * The Research Library's `paper_chunks.embedding` vectors were generated by
 * `wfmlabs-fleet-research/02-working/generate-embeddings.ts` with the local model
 * `Xenova/all-MiniLM-L6-v2` (384-dim, mean pooling + L2 normalize, via @xenova/transformers,
 * no API key). To do semantic kNN, the QUERY must be embedded into the SAME space with the
 * SAME model/pooling/normalization — anything else makes cosine distance meaningless.
 *
 * Runtime: this runs in the Node serverless route (not edge). The model (~quantized) is
 * fetched once per cold lambda and cached under /tmp (the only writable path on Vercel);
 * the pipeline is memoized per instance so warm invocations reuse it. If anything fails
 * (download, ONNX, OOM) we return null and the caller falls back to keyword retrieval —
 * embedding must never take the whole route down.
 */

export const EMBED_MODEL = 'Xenova/all-MiniLM-L6-v2'
export const EMBED_DIMS = 384

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let pipePromise: Promise<any> | null = null

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function getEmbedder(): Promise<any> {
  if (!pipePromise) {
    pipePromise = (async () => {
      const { pipeline, env } = await import('@xenova/transformers')
      // Writable cache on Vercel; persists across warm invocations of the same instance.
      env.cacheDir = process.env.TRANSFORMERS_CACHE || '/tmp/hf-cache'
      env.allowRemoteModels = true
      // Single-threaded WASM/ONNX is plenty for one short query and avoids thread issues in serverless.
      if (env.backends?.onnx?.wasm) env.backends.onnx.wasm.numThreads = 1
      return pipeline('feature-extraction', EMBED_MODEL)
    })().catch((e) => {
      // Reset so a later request can retry a fresh load rather than caching the rejection forever.
      pipePromise = null
      throw e
    })
  }
  return pipePromise
}

/**
 * Embed a query string into the 384-dim all-MiniLM-L6-v2 space (mean-pooled, L2-normalized).
 * Returns null on any failure so the caller can fall back to keyword retrieval.
 */
export async function embedQuery(text: string): Promise<number[] | null> {
  const clean = (text || '').trim()
  if (!clean) return null
  try {
    const embedder = await getEmbedder()
    const out = await embedder(clean.slice(0, 2000), { pooling: 'mean', normalize: true })
    const vec = Array.from(out.data as Float32Array).slice(0, EMBED_DIMS) as number[]
    if (vec.length !== EMBED_DIMS) return null
    return vec
  } catch (e) {
    console.error('[beacon/embed] embedding failed, falling back to keyword:', String(e).slice(0, 200))
    return null
  }
}

/** pgvector literal for a parameterized `$n::vector` cast. */
export function toVectorLiteral(vec: number[]): string {
  return `[${vec.join(',')}]`
}
