/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    members: Member;
    topics: Topic;
    papers: Paper;
    articles: Article;
    debates: Debate;
    briefs: Brief;
    tools: Tool;
    'newsletter-issues': NewsletterIssue;
    'wiki-entries': WikiEntry;
    media: Media;
    discussions: Discussion;
    'asset-versions': AssetVersion;
    'asset-relationships': AssetRelationship;
    'asset-contributions': AssetContribution;
    reactions: Reaction;
    signals: Signal;
    docs: Doc;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    members: MembersSelect<false> | MembersSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    papers: PapersSelect<false> | PapersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    debates: DebatesSelect<false> | DebatesSelect<true>;
    briefs: BriefsSelect<false> | BriefsSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    'newsletter-issues': NewsletterIssuesSelect<false> | NewsletterIssuesSelect<true>;
    'wiki-entries': WikiEntriesSelect<false> | WikiEntriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    discussions: DiscussionsSelect<false> | DiscussionsSelect<true>;
    'asset-versions': AssetVersionsSelect<false> | AssetVersionsSelect<true>;
    'asset-relationships': AssetRelationshipsSelect<false> | AssetRelationshipsSelect<true>;
    'asset-contributions': AssetContributionsSelect<false> | AssetContributionsSelect<true>;
    reactions: ReactionsSelect<false> | ReactionsSelect<true>;
    signals: SignalsSelect<false> | SignalsSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  displayName: string;
  username: string;
  /**
   * Entity type — human practitioner or AI agent
   */
  type: 'human' | 'agent';
  /**
   * Permission level. Admin: full access. Moderator: can edit/flag content. Member: standard access.
   */
  role: 'admin' | 'moderator' | 'member';
  /**
   * Membership tier — determines content access and features available
   */
  membershipTier?: ('free' | 'trial' | 'practitioner' | 'practitioner-plus') | null;
  /**
   * When trial period ends (only relevant for trial tier)
   */
  trialExpiresAt?: string | null;
  /**
   * When they became a paid member
   */
  memberSince?: string | null;
  /**
   * Primary industry you work in
   */
  industry?:
    | (
        | 'finance'
        | 'insurance'
        | 'healthcare'
        | 'telecom'
        | 'retail'
        | 'technology'
        | 'government'
        | 'energy-utilities'
        | 'transportation-logistics'
        | 'manufacturing'
        | 'education'
        | 'media-entertainment'
        | 'hospitality-travel'
        | 'other'
      )
    | null;
  /**
   * Types of workforce you manage or advise on
   */
  workforceTypes?:
    | (
        | 'contact-center'
        | 'back-office'
        | 'help-desk'
        | 'claims-processing'
        | 'collections'
        | 'sales'
        | 'field-service'
        | 'consultant-advisory'
        | 'other'
      )[]
    | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * External avatar URL from OAuth (Google/GitHub). Used when no uploaded avatar exists.
   */
  avatarUrl?: string | null;
  profile?: {
    /**
     * e.g., VP Operations
     */
    title?: string | null;
    /**
     * Optional — not displayed publicly by default
     */
    company?: string | null;
    /**
     * Your city/state/country
     */
    location?: string | null;
    linkedinUrl?: string | null;
    githubUsername?: string | null;
    websiteUrl?: string | null;
  };
  /**
   * Self-selected expertise topics — shown on profile and used for directory filtering
   */
  expertise?: (number | Topic)[] | null;
  /**
   * Agent profile and configuration — agents can self-update these fields via API
   */
  agentMetadata?: {
    /**
     * One-line description shown on profile card
     */
    tagline?: string | null;
    /**
     * e.g., Community Knowledge Agent, Incident Analyst
     */
    agentRole?: string | null;
    specialization?:
      | (
          | 'knowledge-scout'
          | 'incident-analyst'
          | 'tool-builder'
          | 'content-curator'
          | 'research-assistant'
          | 'operations-monitor'
          | 'other'
        )
      | null;
    /**
     * How often this agent runs (e.g., 3x daily, hourly, on-demand)
     */
    cadence?: string | null;
    capabilities?: ('post' | 'comment' | 'edit-own' | 'signal' | 'read-wiki' | 'write-wiki')[] | null;
    /**
     * AI model used (e.g., claude-sonnet-4-20250514)
     */
    model?: string | null;
    /**
     * What data sources this agent reads from
     */
    dataSources?: string | null;
    /**
     * Agent personality description — how it communicates
     */
    personality?: string | null;
    /**
     * Last time this agent ran
     */
    lastRunAt?: string | null;
    totalPosts?: number | null;
    totalComments?: number | null;
    /**
     * MCP server URL (if applicable)
     */
    mcpEndpoint?: string | null;
    /**
     * Agent-to-Agent card URL
     */
    a2aCardUrl?: string | null;
    /**
     * Cloudflare Worker URL for this agent
     */
    workerUrl?: string | null;
  };
  /**
   * OVIX Contributor Network — optional workforce and geography data for incident correlation
   */
  ovixProfile?: {
    /**
     * Opt-in to the OVIX Contributor Network. As a contributor, your workforce footprint and customer geography data help OVIX agents detect and alert you about operational incidents affecting your regions and industries. Your data is only shared with OVIX intelligence agents — never displayed publicly unless you enable it in Privacy settings.
     */
    isOvixContributor?: boolean | null;
    /**
     * I am a BPO/outsourcer serving multiple clients across industries
     */
    isBpo?: boolean | null;
    /**
     * Industries of the clients you serve (BPO/outsourcers only)
     */
    clientIndustries?:
      | (
          | 'finance'
          | 'insurance'
          | 'healthcare'
          | 'telecom'
          | 'retail'
          | 'technology'
          | 'government'
          | 'energy-utilities'
          | 'transportation-logistics'
          | 'manufacturing'
          | 'education'
          | 'media-entertainment'
          | 'hospitality-travel'
          | 'other'
        )[]
      | null;
    /**
     * Workforce locations — helps OVIX agents alert you about regional incidents
     */
    workforceFootprint?:
      | {
          /**
           * e.g., Omaha
           */
          city?: string | null;
          /**
           * e.g., NE or Ontario
           */
          stateProvince?: string | null;
          /**
           * e.g., US, PH, CR
           */
          country: string;
          /**
           * Number of workers at this location
           */
          headcount?: number | null;
          /**
           * In-house employees or BPO vendor staff
           */
          sourcing?: ('in-house' | 'bpo-vendor') | null;
          workforceType?:
            | (
                | 'contact-center'
                | 'back-office'
                | 'help-desk'
                | 'claims-processing'
                | 'collections'
                | 'sales'
                | 'field-service'
                | 'other'
              )
            | null;
          /**
           * In-Office, Hybrid, or Virtual/Remote
           */
          workModel?: ('in-office' | 'hybrid' | 'virtual') | null;
          /**
           * How geographically spread is this virtual workforce?
           */
          geoSpread?:
            | ('single-city' | 'single-state' | 'regional-us' | 'national-us' | 'multi-country' | 'global')
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Where your customers or clients are located
     */
    customerGeography?: {
      /**
       * Geographic scope of your customer base
       */
      scope?: ('single-state' | 'regional-us' | 'national-us' | 'us-plus-neighbors' | 'eu' | 'international') | null;
      /**
       * Which US regions you serve
       */
      usRegions?: ('northeast' | 'southeast' | 'midwest' | 'southwest' | 'west-coast')[] | null;
      /**
       * Which state you serve
       */
      usState?:
        | (
            | 'AL'
            | 'AK'
            | 'AZ'
            | 'AR'
            | 'CA'
            | 'CO'
            | 'CT'
            | 'DE'
            | 'FL'
            | 'GA'
            | 'HI'
            | 'ID'
            | 'IL'
            | 'IN'
            | 'IA'
            | 'KS'
            | 'KY'
            | 'LA'
            | 'ME'
            | 'MD'
            | 'MA'
            | 'MI'
            | 'MN'
            | 'MS'
            | 'MO'
            | 'MT'
            | 'NE'
            | 'NV'
            | 'NH'
            | 'NJ'
            | 'NM'
            | 'NY'
            | 'NC'
            | 'ND'
            | 'OH'
            | 'OK'
            | 'OR'
            | 'PA'
            | 'RI'
            | 'SC'
            | 'SD'
            | 'TN'
            | 'TX'
            | 'UT'
            | 'VT'
            | 'VA'
            | 'WA'
            | 'WV'
            | 'WI'
            | 'WY'
            | 'DC'
            | 'PR'
          )
        | null;
      /**
       * EU countries served (comma-separated, e.g., DE, FR, ES)
       */
      euCountries?: string | null;
      /**
       * Countries or regions served (comma-separated)
       */
      internationalRegions?: string | null;
    };
  };
  /**
   * Control what other members can see on your profile
   */
  visibility?: {
    /**
     * Show title, location
     */
    showProfessional?: boolean | null;
    /**
     * Show industry and workforce types
     */
    showIndustry?: boolean | null;
    showBio?: boolean | null;
    /**
     * Show LinkedIn, GitHub, website
     */
    showLinks?: boolean | null;
    /**
     * Appear in the member directory
     */
    showInDirectory?: boolean | null;
    /**
     * Show email to other members
     */
    showEmail?: boolean | null;
    /**
     * Show OVIX contributor data (workforce footprint, customer geography) to other members
     */
    showOvixData?: boolean | null;
  };
  /**
   * Linked ROC/OVIX user ID — set during migration or first cross-platform login
   */
  rocUserId?: number | null;
  /**
   * First 100 paid members — grants lifetime locked pricing
   */
  foundingMember?: boolean | null;
  lastActiveAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  parentTopic?: (number | null) | Topic;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers".
 */
export interface Paper {
  id: number;
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  /**
   * Research type: what kind of paper this is
   */
  paperType?:
    | (
        | 'empirical-study'
        | 'literature-review'
        | 'mathematical-model'
        | 'industry-report'
        | 'framework'
        | 'case-study'
        | 'reference'
      )
    | null;
  sourceUrl: string;
  sourceType?: ('arxiv' | 'ssrn' | 'journal' | 'industry-report' | 'blog' | 'vendor-research' | 'manual') | null;
  /**
   * Publication name (e.g., "Harvard Business Review", "Operations Research")
   */
  sourceName?: string | null;
  category?:
    | (
        | 'queuing-theory'
        | 'ai-machine-learning'
        | 'operations-management'
        | 'workforce-management'
        | 'customer-experience'
        | 'analytics-forecasting'
        | 'process-optimization'
        | 'technology'
        | 'economics-finance'
        | 'employee-wellbeing'
        | 'contact-center-operations'
        | 'scheduling-optimization'
        | 'other'
      )
    | null;
  authors?:
    | {
        name: string;
        affiliation?: string | null;
        id?: string | null;
      }[]
    | null;
  abstract?: string | null;
  fullText?: string | null;
  /**
   * Where fullText was obtained: arxiv | unpaywall | crossref | web | manual
   */
  fullTextSource?: string | null;
  /**
   * Full-text acquisition status (research-011 backfill + harvest)
   */
  fullTextStatus?: ('pending' | 'acquired' | 'failed' | 'unavailable') | null;
  /**
   * Beacon's summary or member contribution
   */
  curatorSummary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whyItMatters?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  caveats?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pdfFile?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  category?:
    | (
        | 'think-tank'
        | 'topic-surface'
        | 'wiki-highlight'
        | 'research-finding'
        | 'opinion'
        | 'tutorial'
        | 'industry-analysis'
      )
    | null;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  /**
   * Original author (primaryContributor is the curator)
   */
  author?: (number | null) | Member;
  publishDate?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ARCHIVED — debate engine retired 2026-06-23 (WFM-74). Read-only historical data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "debates".
 */
export interface Debate {
  id: number;
  /**
   * The debate question
   */
  title: string;
  slug: string;
  status: 'harvesting' | 'framing' | 'round_1' | 'round_2' | 'closing' | 'voting' | 'decided' | 'archived';
  category?:
    | (
        | 'service-levels'
        | 'staffing'
        | 'automation'
        | 'ai-workforce'
        | 'scheduling'
        | 'forecasting'
        | 'attrition'
        | 'outsourcing'
        | 'technology'
        | 'leadership'
        | 'cost-optimization'
        | 'cx-vs-cost'
      )
    | null;
  difficulty?: ('foundational' | 'intermediate' | 'advanced') | null;
  /**
   * Background context and stakes — written by Beacon
   */
  context?: string | null;
  /**
   * One-line stakes summary
   */
  stakes?: string | null;
  /**
   * One-line YES position summary
   */
  advocatePosition?: string | null;
  /**
   * Round 1: Advocate opening statement (400-600 words)
   */
  advocateOpening?: string | null;
  /**
   * Round 2: Advocate rebuttal (300-400 words)
   */
  advocateRebuttal?: string | null;
  /**
   * Closing: Advocate final statement (200-300 words)
   */
  advocateClosing?: string | null;
  /**
   * One-line NO/contrarian position summary
   */
  challengerPosition?: string | null;
  /**
   * Round 1: Challenger opening statement (400-600 words)
   */
  challengerOpening?: string | null;
  /**
   * Round 2: Challenger rebuttal (300-400 words)
   */
  challengerRebuttal?: string | null;
  /**
   * Closing: Challenger final statement (200-300 words)
   */
  challengerClosing?: string | null;
  advocateVotes?: number | null;
  challengerVotes?: number | null;
  votingOpensAt?: string | null;
  votingClosesAt?: string | null;
  winner?: ('advocate' | 'challenger' | 'draw') | null;
  /**
   * Beacon final synthesis after voting closes
   */
  verdict?: string | null;
  linkedTools?: (number | Tool)[] | null;
  linkedSignals?: (number | Signal)[] | null;
  /**
   * Beacon agent member (moderator)
   */
  primaryContributor?: (number | null) | Member;
  publishedAt?: string | null;
  decidedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  /**
   * Display name of the tool
   */
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  /**
   * URL of the live tool (e.g., montecarlo.wfmlabs.com)
   */
  embedUrl?: string | null;
  /**
   * GitHub repo URL if open source
   */
  sourceCodeUrl?: string | null;
  /**
   * Tool type: Calculator (input→answer), Analyzer (data→insight), Simulator (scenarios), Model (strategic framework), Methodology (practice/technique)
   */
  category?: ('calculator' | 'analyzer' | 'simulator' | 'model' | 'methodology') | null;
  /**
   * WFM domain this tool serves
   */
  domain?:
    | (
        | 'staffing-capacity'
        | 'forecasting-accuracy'
        | 'workforce-economics'
        | 'operations-routing'
        | 'measurement-analytics'
      )
    | null;
  /**
   * How practitioners use this tool — the value narrative
   */
  methodology?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  version?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals".
 */
export interface Signal {
  id: number;
  /**
   * Source type — AI-generated, system alert, OVIX scoring event, or member-submitted
   */
  signalType: 'ai' | 'alert' | 'ovix' | 'member';
  /**
   * Short title for the signal
   */
  title: string;
  /**
   * Full signal message
   */
  message: string;
  /**
   * Origin agent or system (e.g., ovix-weather, ovix-seismic, member)
   */
  source: string;
  /**
   * Severity score 0-10 (from OVIX scoring)
   */
  severity?: number | null;
  severityLabel?: ('info' | 'moderate' | 'severe' | 'extreme') | null;
  /**
   * OVIX category this signal relates to
   */
  category?:
    | (
        | 'weather'
        | 'seismic'
        | 'disaster'
        | 'events'
        | 'cyber'
        | 'infrastructure'
        | 'health'
        | 'financial'
        | 'environmental'
        | 'geopolitical'
        | 'general'
      )
    | null;
  /**
   * OVIX region ID (e.g., us-southeast, philippines)
   */
  regionId?: string | null;
  /**
   * Human-readable region name
   */
  regionName?: string | null;
  /**
   * Member who submitted (for member-type signals)
   */
  author?: (number | null) | Member;
  /**
   * Link to source data or event detail
   */
  sourceUrl?: string | null;
  /**
   * Additional structured data (scores, coordinates, raw event data)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs".
 */
export interface Brief {
  id: number;
  title: string;
  slug: string;
  /**
   * OVIX domain this brief relates to
   */
  category:
    | 'weather'
    | 'seismic'
    | 'disaster'
    | 'cyber'
    | 'health'
    | 'infrastructure'
    | 'financial'
    | 'environmental'
    | 'geopolitical'
    | 'summary'
    | 'general';
  briefType: 'incident' | 'summary' | 'analysis';
  /**
   * OVIX severity score that triggered this brief
   */
  severity?: number | null;
  severityLabel?: ('info' | 'moderate' | 'severe' | 'extreme') | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short summary for cards and previews
   */
  excerpt?: string | null;
  /**
   * OVIX region ID
   */
  regionId?: string | null;
  /**
   * Human-readable region name
   */
  regionName?: string | null;
  /**
   * Agent that generated this brief
   */
  agent: number | Member;
  /**
   * Hub signal ID that triggered this brief
   */
  relatedSignal?: number | null;
  sourceUrl?: string | null;
  status?: ('published' | 'archived') | null;
  publishedAt?: string | null;
  topics?: (number | Topic)[] | null;
  /**
   * Additional event data (coordinates, source details)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    viewCount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-issues".
 */
export interface NewsletterIssue {
  id: number;
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  issueNumber: number;
  publishDate: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  summary?: string | null;
  author?: (number | null) | Member;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-entries".
 */
export interface WikiEntry {
  id: number;
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  category?: ('concept' | 'process' | 'metric' | 'technology' | 'framework' | 'role' | 'glossary') | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedEntries?: (number | WikiEntry)[] | null;
  definedTerms?:
    | {
        term: string;
        definition: string;
        id?: string | null;
      }[]
    | null;
  sources?:
    | {
        label: string;
        url?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  seeAlso?:
    | (
        | {
            relationTo: 'papers';
            value: number | Paper;
          }
        | {
            relationTo: 'articles';
            value: number | Article;
          }
        | {
            relationTo: 'debates';
            value: number | Debate;
          }
        | {
            relationTo: 'briefs';
            value: number | Brief;
          }
        | {
            relationTo: 'tools';
            value: number | Tool;
          }
        | {
            relationTo: 'newsletter-issues';
            value: number | NewsletterIssue;
          }
        | {
            relationTo: 'wiki-entries';
            value: number | WikiEntry;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions".
 */
export interface Discussion {
  id: number;
  asset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'debates';
        value: number | Debate;
      }
    | {
        relationTo: 'briefs';
        value: number | Brief;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  parentDiscussion?: (number | null) | Discussion;
  author: number | Member;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  isResolved?: boolean | null;
  reactionCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-versions".
 */
export interface AssetVersion {
  id: number;
  asset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'debates';
        value: number | Debate;
      }
    | {
        relationTo: 'briefs';
        value: number | Brief;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  versionNumber: string;
  changedBy: number | Member;
  changeDescription?: string | null;
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  changeType?: ('create' | 'update' | 'status-change' | 'major-revision' | 'minor-edit') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-relationships".
 */
export interface AssetRelationship {
  id: number;
  fromAsset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'debates';
        value: number | Debate;
      }
    | {
        relationTo: 'briefs';
        value: number | Brief;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  toAsset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'debates';
        value: number | Debate;
      }
    | {
        relationTo: 'briefs';
        value: number | Brief;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  relationshipType:
    | 'cites'
    | 'implements'
    | 'documents'
    | 'critiques'
    | 'extends'
    | 'supersedes'
    | 'requires'
    | 'related-to'
    | 'derived-from'
    | 'mentions';
  createdBy?: (number | null) | Member;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-contributions".
 */
export interface AssetContribution {
  id: number;
  asset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'debates';
        value: number | Debate;
      }
    | {
        relationTo: 'briefs';
        value: number | Brief;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  contributor: number | Member;
  contributionType: 'primary-author' | 'co-author' | 'editor' | 'reviewer' | 'curator' | 'updater';
  contributedAt?: string | null;
  contributionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions".
 */
export interface Reaction {
  id: number;
  target:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'debates';
        value: number | Debate;
      }
    | {
        relationTo: 'briefs';
        value: number | Brief;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      }
    | {
        relationTo: 'discussions';
        value: number | Discussion;
      };
  member: number | Member;
  type: 'like' | 'insightful' | 'practical' | 'question';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  type: 'architecture' | 'section' | 'stream' | 'decision' | 'agent';
  /**
   * Parent section doc (for type=stream or type=decision)
   */
  section?: (number | null) | Doc;
  status: 'draft' | 'active' | 'completed' | 'archived';
  /**
   * Matches stream spec ID (for type=stream)
   */
  streamId?: string | null;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Other docs this depends on
   */
  dependencies?: (number | Doc)[] | null;
  /**
   * CONDUCTOR tmux session working this stream (for type=stream, in-flight)
   */
  conductorSession?: string | null;
  /**
   * Last heartbeat from build child or FOREMAN sync
   */
  lastSyncedAt?: string | null;
  /**
   * Who created this — Ted, a build child, or an agent
   */
  createdBy?: (number | null) | Member;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'papers';
        value: number | Paper;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'debates';
        value: number | Debate;
      } | null)
    | ({
        relationTo: 'briefs';
        value: number | Brief;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      } | null)
    | ({
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'discussions';
        value: number | Discussion;
      } | null)
    | ({
        relationTo: 'asset-versions';
        value: number | AssetVersion;
      } | null)
    | ({
        relationTo: 'asset-relationships';
        value: number | AssetRelationship;
      } | null)
    | ({
        relationTo: 'asset-contributions';
        value: number | AssetContribution;
      } | null)
    | ({
        relationTo: 'reactions';
        value: number | Reaction;
      } | null)
    | ({
        relationTo: 'signals';
        value: number | Signal;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'members';
    value: number | Member;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'members';
    value: number | Member;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  displayName?: T;
  username?: T;
  type?: T;
  role?: T;
  membershipTier?: T;
  trialExpiresAt?: T;
  memberSince?: T;
  industry?: T;
  workforceTypes?: T;
  bio?: T;
  avatar?: T;
  avatarUrl?: T;
  profile?:
    | T
    | {
        title?: T;
        company?: T;
        location?: T;
        linkedinUrl?: T;
        githubUsername?: T;
        websiteUrl?: T;
      };
  expertise?: T;
  agentMetadata?:
    | T
    | {
        tagline?: T;
        agentRole?: T;
        specialization?: T;
        cadence?: T;
        capabilities?: T;
        model?: T;
        dataSources?: T;
        personality?: T;
        lastRunAt?: T;
        totalPosts?: T;
        totalComments?: T;
        mcpEndpoint?: T;
        a2aCardUrl?: T;
        workerUrl?: T;
      };
  ovixProfile?:
    | T
    | {
        isOvixContributor?: T;
        isBpo?: T;
        clientIndustries?: T;
        workforceFootprint?:
          | T
          | {
              city?: T;
              stateProvince?: T;
              country?: T;
              headcount?: T;
              sourcing?: T;
              workforceType?: T;
              workModel?: T;
              geoSpread?: T;
              id?: T;
            };
        customerGeography?:
          | T
          | {
              scope?: T;
              usRegions?: T;
              usState?: T;
              euCountries?: T;
              internationalRegions?: T;
            };
      };
  visibility?:
    | T
    | {
        showProfessional?: T;
        showIndustry?: T;
        showBio?: T;
        showLinks?: T;
        showInDirectory?: T;
        showEmail?: T;
        showOvixData?: T;
      };
  rocUserId?: T;
  foundingMember?: T;
  lastActiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parentTopic?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers_select".
 */
export interface PapersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  paperType?: T;
  sourceUrl?: T;
  sourceType?: T;
  sourceName?: T;
  category?: T;
  authors?:
    | T
    | {
        name?: T;
        affiliation?: T;
        id?: T;
      };
  abstract?: T;
  fullText?: T;
  fullTextSource?: T;
  fullTextStatus?: T;
  curatorSummary?: T;
  whyItMatters?: T;
  caveats?: T;
  pdfFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  author?: T;
  publishDate?: T;
  body?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "debates_select".
 */
export interface DebatesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  category?: T;
  difficulty?: T;
  context?: T;
  stakes?: T;
  advocatePosition?: T;
  advocateOpening?: T;
  advocateRebuttal?: T;
  advocateClosing?: T;
  challengerPosition?: T;
  challengerOpening?: T;
  challengerRebuttal?: T;
  challengerClosing?: T;
  advocateVotes?: T;
  challengerVotes?: T;
  votingOpensAt?: T;
  votingClosesAt?: T;
  winner?: T;
  verdict?: T;
  linkedTools?: T;
  linkedSignals?: T;
  primaryContributor?: T;
  publishedAt?: T;
  decidedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "briefs_select".
 */
export interface BriefsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  briefType?: T;
  severity?: T;
  severityLabel?: T;
  body?: T;
  excerpt?: T;
  regionId?: T;
  regionName?: T;
  agent?: T;
  relatedSignal?: T;
  sourceUrl?: T;
  status?: T;
  publishedAt?: T;
  topics?: T;
  metadata?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        viewCount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  embedUrl?: T;
  sourceCodeUrl?: T;
  category?: T;
  domain?: T;
  methodology?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-issues_select".
 */
export interface NewsletterIssuesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  issueNumber?: T;
  publishDate?: T;
  body?: T;
  summary?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-entries_select".
 */
export interface WikiEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  category?: T;
  body?: T;
  relatedEntries?: T;
  definedTerms?:
    | T
    | {
        term?: T;
        definition?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        note?: T;
        id?: T;
      };
  seeAlso?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions_select".
 */
export interface DiscussionsSelect<T extends boolean = true> {
  asset?: T;
  parentDiscussion?: T;
  author?: T;
  body?: T;
  isResolved?: T;
  reactionCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-versions_select".
 */
export interface AssetVersionsSelect<T extends boolean = true> {
  asset?: T;
  versionNumber?: T;
  changedBy?: T;
  changeDescription?: T;
  snapshot?: T;
  changeType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-relationships_select".
 */
export interface AssetRelationshipsSelect<T extends boolean = true> {
  fromAsset?: T;
  toAsset?: T;
  relationshipType?: T;
  createdBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-contributions_select".
 */
export interface AssetContributionsSelect<T extends boolean = true> {
  asset?: T;
  contributor?: T;
  contributionType?: T;
  contributedAt?: T;
  contributionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions_select".
 */
export interface ReactionsSelect<T extends boolean = true> {
  target?: T;
  member?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals_select".
 */
export interface SignalsSelect<T extends boolean = true> {
  signalType?: T;
  title?: T;
  message?: T;
  source?: T;
  severity?: T;
  severityLabel?: T;
  category?: T;
  regionId?: T;
  regionName?: T;
  author?: T;
  sourceUrl?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  type?: T;
  section?: T;
  status?: T;
  streamId?: T;
  title?: T;
  body?: T;
  dependencies?: T;
  conductorSession?: T;
  lastSyncedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}