/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    members: Member;
    topics: Topic;
    papers: Paper;
    articles: Article;
    tools: Tool;
    'newsletter-issues': NewsletterIssue;
    'wiki-entries': WikiEntry;
    media: Media;
    discussions: Discussion;
    'asset-versions': AssetVersion;
    'asset-relationships': AssetRelationship;
    'asset-contributions': AssetContribution;
    reactions: Reaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    members: MembersSelect<false> | MembersSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    papers: PapersSelect<false> | PapersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    'newsletter-issues': NewsletterIssuesSelect<false> | NewsletterIssuesSelect<true>;
    'wiki-entries': WikiEntriesSelect<false> | WikiEntriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    discussions: DiscussionsSelect<false> | DiscussionsSelect<true>;
    'asset-versions': AssetVersionsSelect<false> | AssetVersionsSelect<true>;
    'asset-relationships': AssetRelationshipsSelect<false> | AssetRelationshipsSelect<true>;
    'asset-contributions': AssetContributionsSelect<false> | AssetContributionsSelect<true>;
    reactions: ReactionsSelect<false> | ReactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  displayName: string;
  username: string;
  /**
   * Entity type — human practitioner or AI agent
   */
  type: 'human' | 'agent';
  /**
   * Permission level. Admin: full access. Moderator: can edit/flag content. Member: standard access.
   */
  role: 'admin' | 'moderator' | 'member';
  bio?: string | null;
  avatar?: (number | null) | Media;
  profile?: {
    /**
     * e.g., VP Operations
     */
    title?: string | null;
    company?: string | null;
    location?: string | null;
    linkedinUrl?: string | null;
    githubUsername?: string | null;
    websiteUrl?: string | null;
  };
  /**
   * Agent-specific configuration
   */
  agentMetadata?: {
    tagline?: string | null;
    /**
     * e.g., Research Librarian
     */
    agentRole?: string | null;
    mcpEndpoint?: string | null;
    a2aCardUrl?: string | null;
  };
  /**
   * Self-selected expertise topics — shown on profile and used for directory filtering
   */
  expertise?: (number | Topic)[] | null;
  /**
   * Control what other members can see on your profile
   */
  visibility?: {
    /**
     * Show title, company, location
     */
    showProfessional?: boolean | null;
    showBio?: boolean | null;
    /**
     * Show LinkedIn, GitHub, website
     */
    showLinks?: boolean | null;
    /**
     * Appear in the member directory
     */
    showInDirectory?: boolean | null;
    /**
     * Show email to other members
     */
    showEmail?: boolean | null;
  };
  /**
   * First 100 paid members — grants lifetime locked pricing
   */
  foundingMember?: boolean | null;
  lastActiveAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  parentTopic?: (number | null) | Topic;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers".
 */
export interface Paper {
  id: number;
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  sourceUrl: string;
  sourceType?: ('arxiv' | 'ssrn' | 'journal' | 'industry-report' | 'blog' | 'vendor-research' | 'manual') | null;
  authors?:
    | {
        name: string;
        affiliation?: string | null;
        id?: string | null;
      }[]
    | null;
  abstract?: string | null;
  fullText?: string | null;
  /**
   * Beacon's summary or member contribution
   */
  curatorSummary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whyItMatters?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  caveats?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pdfFile?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  /**
   * Original author (primaryContributor is the curator)
   */
  author?: (number | null) | Member;
  publishDate?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  /**
   * Display name of the tool
   */
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  /**
   * URL of the live tool (e.g., montecarlo.wfmlabs.com)
   */
  embedUrl?: string | null;
  /**
   * GitHub repo URL if open source
   */
  sourceCodeUrl?: string | null;
  category?: ('capacity-planning' | 'forecasting' | 'scheduling' | 'analytics' | 'value-planning' | 'staffing') | null;
  /**
   * How practitioners use this tool — the value narrative
   */
  methodology?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  version?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-issues".
 */
export interface NewsletterIssue {
  id: number;
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  issueNumber: number;
  publishDate: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  summary?: string | null;
  author?: (number | null) | Member;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-entries".
 */
export interface WikiEntry {
  id: number;
  title: string;
  /**
   * URL-safe identifier (auto-generated or manual)
   */
  slug: string;
  primaryContributor: number | Member;
  description?: string | null;
  topics?: (number | Topic)[] | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'proposed' | 'published' | 'refined' | 'mature' | 'deprecated' | 'archived') | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * Days between scheduled reviews
   */
  reviewIntervalDays?: number | null;
  tier?: ('public' | 'free' | 'practitioner' | 'practitioner-plus') | null;
  isFeatured?: boolean | null;
  /**
   * Aggregate statistics (auto-updated)
   */
  stats?: {
    discussionCount?: number | null;
    reactionCount?: number | null;
    contributorCount?: number | null;
    viewCount?: number | null;
    citationCount?: number | null;
  };
  category?: ('concept' | 'process' | 'metric' | 'technology' | 'framework' | 'role' | 'glossary') | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedEntries?: (number | WikiEntry)[] | null;
  definedTerms?:
    | {
        term: string;
        definition: string;
        id?: string | null;
      }[]
    | null;
  sources?:
    | {
        label: string;
        url?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  seeAlso?:
    | (
        | {
            relationTo: 'papers';
            value: number | Paper;
          }
        | {
            relationTo: 'articles';
            value: number | Article;
          }
        | {
            relationTo: 'tools';
            value: number | Tool;
          }
        | {
            relationTo: 'newsletter-issues';
            value: number | NewsletterIssue;
          }
        | {
            relationTo: 'wiki-entries';
            value: number | WikiEntry;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions".
 */
export interface Discussion {
  id: number;
  asset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  parentDiscussion?: (number | null) | Discussion;
  author: number | Member;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  isResolved?: boolean | null;
  reactionCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-versions".
 */
export interface AssetVersion {
  id: number;
  asset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  versionNumber: string;
  changedBy: number | Member;
  changeDescription?: string | null;
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  changeType?: ('create' | 'update' | 'status-change' | 'major-revision' | 'minor-edit') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-relationships".
 */
export interface AssetRelationship {
  id: number;
  fromAsset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  toAsset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  relationshipType:
    | 'cites'
    | 'implements'
    | 'documents'
    | 'critiques'
    | 'extends'
    | 'supersedes'
    | 'requires'
    | 'related-to'
    | 'derived-from'
    | 'mentions';
  createdBy?: (number | null) | Member;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-contributions".
 */
export interface AssetContribution {
  id: number;
  asset:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      };
  contributor: number | Member;
  contributionType: 'primary-author' | 'co-author' | 'editor' | 'reviewer' | 'curator' | 'updater';
  contributedAt?: string | null;
  contributionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions".
 */
export interface Reaction {
  id: number;
  target:
    | {
        relationTo: 'papers';
        value: number | Paper;
      }
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'tools';
        value: number | Tool;
      }
    | {
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      }
    | {
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      }
    | {
        relationTo: 'discussions';
        value: number | Discussion;
      };
  member: number | Member;
  type: 'like' | 'insightful' | 'practical' | 'question';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'papers';
        value: number | Paper;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'newsletter-issues';
        value: number | NewsletterIssue;
      } | null)
    | ({
        relationTo: 'wiki-entries';
        value: number | WikiEntry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'discussions';
        value: number | Discussion;
      } | null)
    | ({
        relationTo: 'asset-versions';
        value: number | AssetVersion;
      } | null)
    | ({
        relationTo: 'asset-relationships';
        value: number | AssetRelationship;
      } | null)
    | ({
        relationTo: 'asset-contributions';
        value: number | AssetContribution;
      } | null)
    | ({
        relationTo: 'reactions';
        value: number | Reaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'members';
    value: number | Member;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'members';
    value: number | Member;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  displayName?: T;
  username?: T;
  type?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  profile?:
    | T
    | {
        title?: T;
        company?: T;
        location?: T;
        linkedinUrl?: T;
        githubUsername?: T;
        websiteUrl?: T;
      };
  agentMetadata?:
    | T
    | {
        tagline?: T;
        agentRole?: T;
        mcpEndpoint?: T;
        a2aCardUrl?: T;
      };
  expertise?: T;
  visibility?:
    | T
    | {
        showProfessional?: T;
        showBio?: T;
        showLinks?: T;
        showInDirectory?: T;
        showEmail?: T;
      };
  foundingMember?: T;
  lastActiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parentTopic?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers_select".
 */
export interface PapersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  sourceUrl?: T;
  sourceType?: T;
  authors?:
    | T
    | {
        name?: T;
        affiliation?: T;
        id?: T;
      };
  abstract?: T;
  fullText?: T;
  curatorSummary?: T;
  whyItMatters?: T;
  caveats?: T;
  pdfFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  author?: T;
  publishDate?: T;
  body?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  embedUrl?: T;
  sourceCodeUrl?: T;
  category?: T;
  methodology?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-issues_select".
 */
export interface NewsletterIssuesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  issueNumber?: T;
  publishDate?: T;
  body?: T;
  summary?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki-entries_select".
 */
export interface WikiEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryContributor?: T;
  description?: T;
  topics?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  reviewedAt?: T;
  reviewIntervalDays?: T;
  tier?: T;
  isFeatured?: T;
  stats?:
    | T
    | {
        discussionCount?: T;
        reactionCount?: T;
        contributorCount?: T;
        viewCount?: T;
        citationCount?: T;
      };
  category?: T;
  body?: T;
  relatedEntries?: T;
  definedTerms?:
    | T
    | {
        term?: T;
        definition?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        note?: T;
        id?: T;
      };
  seeAlso?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussions_select".
 */
export interface DiscussionsSelect<T extends boolean = true> {
  asset?: T;
  parentDiscussion?: T;
  author?: T;
  body?: T;
  isResolved?: T;
  reactionCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-versions_select".
 */
export interface AssetVersionsSelect<T extends boolean = true> {
  asset?: T;
  versionNumber?: T;
  changedBy?: T;
  changeDescription?: T;
  snapshot?: T;
  changeType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-relationships_select".
 */
export interface AssetRelationshipsSelect<T extends boolean = true> {
  fromAsset?: T;
  toAsset?: T;
  relationshipType?: T;
  createdBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-contributions_select".
 */
export interface AssetContributionsSelect<T extends boolean = true> {
  asset?: T;
  contributor?: T;
  contributionType?: T;
  contributedAt?: T;
  contributionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions_select".
 */
export interface ReactionsSelect<T extends boolean = true> {
  target?: T;
  member?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}